### ISSUE TITLE
Render bug

### ISSUE THREAD

**Issue by GavinJoyce** [GavinJoyce/octane-counter#1]
With the following component:

```js
import Component from '@ember/component';
import { tracked } from '@glimmer/tracking';

export default class CounterComponent extends Component {
  @tracked count = 1;

  increment() {
    this.count++;
    setTimeout(() => {
      this.count++;
    }, 1000);
  }
}
```

The `{{count}}` property isn't updating correctly. It seems that the property mutation within the `setTimeout` isn't causing a render.

![counter](https://user-images.githubusercontent.com/2526/53586596-6c47ac80-3b80-11e9-8b32-2a1bf1c5c474.gif)

Here's the same component working on [try.glimmer.com](https://try.glimmerjs.com/?app=JTdCJTIyY29tcG9uZW50cyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJHbGltbWVyQXBwJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDaDElM0VXZWxjb21lJTIwdG8lMjB0aGUlMjBHbGltbWVyJTIwUGxheWdyb3VuZCElM0MlMkZoMSUzRSU1Q24lM0NwJTNFVGhlJTIwYnV0dG9uJTIwd2lsbCUyMGluY3JlbWVudCUyMHRoZSUyMGNvdW50JTIwdHdpY2UuJTIwSXQncyUyMGN1cnJlbnRseSUyMCU3QiU3QmNvdW50JTdEJTdEJTNDJTJGcCUzRSU1Q24lM0NidXR0b24lMjBvbmNsaWNrJTNEJTdCJTdCYWN0aW9uJTIwaW5jcmVtZW50JTdEJTdEJTNFQ2xpY2slM0MlMkZidXR0b24lM0UlMjIlN0QlMkMlMjJjb21wb25lbnQlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZjb21wb25lbnQudHMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyaW1wb3J0JTIwQ29tcG9uZW50JTJDJTIwJTdCJTIwdHJhY2tlZCUyMCU3RCUyMGZyb20lMjAnJTQwZ2xpbW1lciUyRmNvbXBvbmVudCclM0IlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNsYXNzJTIwZXh0ZW5kcyUyMENvbXBvbmVudCUyMCU3QiU1Q24lMjAlMjAlNDB0cmFja2VkJTIwY291bnQlMjAlM0QlMjAxJTNCJTVDbiUyMCUyMGluY3JlbWVudCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHRoaXMuY291bnQlMkIlMkIlM0IlNUNuJTIwJTIwJTIwJTIwc2V0VGltZW91dCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0aGlzLmNvdW50JTJCJTJCJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCUyQyUyMDEwMDApJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlN0QlN0QlNUQlMkMlMjJoZWxwZXJzJTIyJTNBJTVCJTVEJTdE)

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/emberjs/ember.js/pull/17682 once the latest ember-source canary build is published and you update to it...

**Comment by GavinJoyce** [comment]
Confirmed fixed with the latest build, thanks!:

![fixed](https://user-images.githubusercontent.com/2526/53614568-4c40d900-3bd2-11e9-9369-ddc1b774952f.gif)
